#!/usr/bin/env python3
"""Generate WorldGraph research corpus manifests and validation output (issue #200)."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from spike.worldgraph.manifest_builder import build_manifest  # noqa: E402
from spike.worldgraph.manifest_schema import validate_manifest_v0  # noqa: E402
from spike.worldgraph.research_corpus import (  # noqa: E402
    CORPUS_ROOT,
    MANIFESTS_DIR,
    VALIDATION_RESULTS_PATH,
)

OBSERVED_AT = "2026-07-22T12:00:00+00:00"
LAST_CHECKED = "2026-07-22"

# Research-only corpus seeds: stable public sources, no auth bypass.
CORPUS_SEEDS: list[dict[str, Any]] = [
    # --- interactive_narrative (5) ---
    {
        "id": "wg-corpus-001",
        "name": "AI Dungeon",
        "category": "interactive_narrative",
        "canonical_source": "https://play.aidungeon.com/",
        "qualification": "qualifies",
        "summary": "Text-first interactive fiction where player actions and AI narration co-author persistent adventures.",
        "creator": "Latitude",
        "operator": "Latitude",
        "entry_point": "https://play.aidungeon.com/",
        "accessibility": "free_account_required",
        "ai_role": "Runtime LLM generates story branches, NPC dialogue, and world reactions to player commands.",
        "persistence": "saved_adventures_and_scenario_state",
        "agents_mechanics": "Turn-based text commands with scenario memory and character state.",
        "platform_runtime": "Web",
        "modalities": ["text"],
        "interaction_model": "text_command_narrative",
        "setting": "User-selected or custom scenarios with defined lore prompts.",
        "characters": "AI narrator and scenario NPCs",
        "license_disclosed": "unknown",
        "safety_disclosed": "13+ terms referenced on parent site",
        "criteria_evidence": {
            "rule_1": "play.aidungeon.com resolves to playable web client.",
            "rule_2": "Players issue actions that change story state.",
            "rule_3": "Scenarios define setting, characters, and narrative bounds.",
            "rule_4": "Adventures and scenarios persist across sessions.",
            "rule_5": "Core loop is AI-authored narrative at runtime.",
            "rule_6": "Latitude named as operator on aidungeon.com.",
            "rule_7": "Account signup and terms linked from product pages.",
        },
        "unknown_manifest_fields": ["trust.license_status", "ai_role.model_disclosures", "experience.age_guidance"],
        "reviewer_notes": "Canonical narrative-world pattern; model vendor not always disclosed per scenario.",
        "confidence": 0.88,
    },
    {
        "id": "wg-corpus-002",
        "name": "Character.AI",
        "category": "interactive_narrative",
        "canonical_source": "https://character.ai/",
        "qualification": "qualifies",
        "summary": "Character-driven chat worlds where users interact with authored personas in bounded scenes.",
        "creator": "Character Technologies",
        "operator": "Character Technologies",
        "entry_point": "https://character.ai/",
        "accessibility": "free_account_required",
        "ai_role": "Runtime character models drive persona dialogue and multi-character scenes.",
        "persistence": "chat_history_and_character_memory",
        "agents_mechanics": "Persona cards, group scenes, and user-authored character definitions.",
        "platform_runtime": "Web and mobile apps",
        "modalities": ["text", "voice"],
        "interaction_model": "character_chat_session",
        "setting": "Persona-specific backstory and scene prompts.",
        "characters": "User-facing AI characters and scenes",
        "license_disclosed": "unknown",
        "safety_disclosed": "Community guidelines and age gate documented",
        "criteria_evidence": {
            "rule_1": "character.ai public homepage links to chat entry.",
            "rule_2": "Users send messages that alter conversation state.",
            "rule_3": "Each character/scene defines bounded persona context.",
            "rule_4": "Chat threads persist for logged-in users.",
            "rule_5": "Character responses are AI-generated at runtime.",
            "rule_6": "Character Technologies identified on site footer/about.",
            "rule_7": "Safety center and terms published.",
        },
        "unknown_manifest_fields": ["ai_role.model_disclosures", "trust.license_status"],
        "reviewer_notes": "Platform hosts many worlds; corpus entry treats the Scenes/Characters product class.",
        "confidence": 0.86,
    },
    {
        "id": "wg-corpus-003",
        "name": "Hidden Door",
        "category": "interactive_narrative",
        "canonical_source": "https://www.hiddendoor.co/",
        "qualification": "qualifies",
        "summary": "AI-native narrative game where players co-create story cards inside a defined fiction.",
        "creator": "Hidden Door",
        "entry_point": "https://www.hiddendoor.co/",
        "accessibility": "waitlist_or_invite",
        "ai_role": "Generative narrative engine produces scenes, characters, and outcomes from player choices.",
        "persistence": "session_story_state",
        "agents_mechanics": "Card-based story progression with character and plot mechanics.",
        "platform_runtime": "Web",
        "modalities": ["text"],
        "interaction_model": "choice_driven_narrative",
        "setting": "Author-defined fiction frames on marketing and demo materials.",
        "characters": "AI-generated cast within story frames",
        "license_disclosed": "unknown",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "Official site documents product with demo/waitlist entry.",
            "rule_2": "Marketing describes player choices affecting story outcomes.",
            "rule_3": "Story frames bound setting and cast.",
            "rule_4": "Demo sessions imply saved story progression.",
            "rule_5": "AI story generation is core product claim.",
            "rule_6": "Hidden Door named as creator on site.",
            "rule_7": "Limited public age/safety copy; marked unknown where absent.",
        },
        "unknown_manifest_fields": ["experience.age_guidance", "trust.license_status"],
        "reviewer_notes": "Access may be invite-limited; still reviewable from public materials.",
        "confidence": 0.78,
    },
    {
        "id": "wg-corpus-004",
        "name": "Friends & Fables",
        "category": "interactive_narrative",
        "canonical_source": "https://www.friendsandfables.ai/",
        "qualification": "qualifies",
        "summary": "AI game master runs tabletop-style RPG sessions with persistent party state.",
        "creator": "Friends & Fables",
        "entry_point": "https://www.friendsandfables.ai/",
        "accessibility": "free_account_required",
        "ai_role": "AI GM narrates scenes, adjudicates rules, and voices NPCs at runtime.",
        "persistence": "campaign_and_character_sheets",
        "agents_mechanics": "Turn-based RPG mechanics with inventory and party state.",
        "platform_runtime": "Web",
        "modalities": ["text", "voice"],
        "interaction_model": "tabletop_rpg_session",
        "setting": "Campaign settings with rule systems.",
        "characters": "AI GM and NPC party",
        "license_disclosed": "unknown",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "Public marketing site links to playable product.",
            "rule_2": "Players take actions within RPG sessions.",
            "rule_3": "Campaign settings and rules documented.",
            "rule_4": "Character/campaign persistence advertised.",
            "rule_5": "AI GM is explicit product centerpiece.",
            "rule_6": "Friends & Fables named on site.",
            "rule_7": "Terms linked; age guidance not explicit.",
        },
        "unknown_manifest_fields": ["experience.age_guidance", "ai_role.model_disclosures"],
        "reviewer_notes": "Strong narrative+RPG hybrid qualifying pattern.",
        "confidence": 0.84,
    },
    {
        "id": "wg-corpus-005",
        "name": "Charisma.ai",
        "category": "interactive_narrative",
        "canonical_source": "https://charisma.ai/",
        "qualification": "qualifies",
        "summary": "Interactive story experiences with AI-driven characters and branching dialogue graphs.",
        "creator": "Charisma.ai",
        "entry_point": "https://charisma.ai/",
        "accessibility": "public_demos_and_studio_access",
        "ai_role": "Character AI runs dialogue graphs and emotional state during interactive stories.",
        "persistence": "story_session_checkpoints",
        "agents_mechanics": "Branching dialogue graphs and character emotion models.",
        "platform_runtime": "Web",
        "modalities": ["text", "voice"],
        "interaction_model": "branching_dialogue",
        "setting": "Per-experience story worlds (e.g., licensed IP demos).",
        "characters": "Charisma-powered story characters",
        "license_disclosed": "unknown",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "charisma.ai hosts demos and product entry.",
            "rule_2": "Users interact with branching story scenes.",
            "rule_3": "Dialogue graphs define bounded narrative paths.",
            "rule_4": "Session checkpoints described in product docs.",
            "rule_5": "Character AI runtime explicitly documented.",
            "rule_6": "Charisma.ai Ltd identified on site.",
            "rule_7": "Public pages lack detailed age ratings.",
        },
        "unknown_manifest_fields": ["experience.age_guidance", "trust.license_status"],
        "reviewer_notes": "Also sells tooling; corpus entry focuses on playable story experiences.",
        "confidence": 0.82,
    },
    # --- ai_spatial (5) ---
    {
        "id": "wg-corpus-006",
        "name": "World Labs Marble",
        "category": "ai_spatial",
        "canonical_source": "https://www.worldlabs.ai/",
        "qualification": "qualifies",
        "summary": "AI-generated explorable 3D environments users can navigate as spatial worlds.",
        "creator": "World Labs",
        "entry_point": "https://www.worldlabs.ai/",
        "accessibility": "public_waitlist_and_demos",
        "ai_role": "Generative world models produce explorable 3D scenes from prompts or images.",
        "persistence": "saved_world_versions",
        "agents_mechanics": "Spatial exploration with generated geometry and materials.",
        "platform_runtime": "Web",
        "modalities": ["3d"],
        "interaction_model": "spatial_exploration",
        "setting": "User-authored or prompt-defined spatial scenes.",
        "license_disclosed": "unknown",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "worldlabs.ai documents Marble with public materials.",
            "rule_2": "Users explore navigable 3D environments.",
            "rule_3": "Each generated world is a bounded spatial scene.",
            "rule_4": "Saved/exported world versions described.",
            "rule_5": "AI world generation is core product.",
            "rule_6": "World Labs named as creator.",
            "rule_7": "Safety/age not disclosed on landing; unknown recorded.",
        },
        "unknown_manifest_fields": ["experience.age_guidance", "trust.license_status"],
        "reviewer_notes": "Reference spatial-world pattern cited in issue scope.",
        "confidence": 0.8,
    },
    {
        "id": "wg-corpus-007",
        "name": "Blockade Labs Skybox",
        "category": "ai_spatial",
        "canonical_source": "https://skybox.blockadelabs.com/",
        "qualification": "qualifies",
        "summary": "Generative 360° skybox worlds users preview and explore in-browser.",
        "creator": "Blockade Labs",
        "entry_point": "https://skybox.blockadelabs.com/",
        "accessibility": "free_account_optional",
        "ai_role": "AI generates immersive 360 environments from text prompts.",
        "persistence": "saved_skybox_library",
        "agents_mechanics": "Panoramic exploration of generated environments.",
        "platform_runtime": "Web",
        "modalities": ["3d", "360_image"],
        "interaction_model": "panoramic_exploration",
        "setting": "Prompt-defined panoramic scenes.",
        "license_disclosed": "commercial terms on site",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "skybox.blockadelabs.com is stable public entry.",
            "rule_2": "Users navigate generated environments interactively.",
            "rule_3": "Prompt constrains scene content.",
            "rule_4": "User skybox libraries persist when logged in.",
            "rule_5": "Generative AI is the product core.",
            "rule_6": "Blockade Labs identified.",
            "rule_7": "Terms present; age guidance unknown.",
        },
        "unknown_manifest_fields": ["experience.age_guidance"],
        "reviewer_notes": "Borderline tool-vs-world; qualifies due to explorable bounded scenes.",
        "confidence": 0.76,
    },
    {
        "id": "wg-corpus-008",
        "name": "Luma Dream Machine",
        "category": "ai_spatial",
        "canonical_source": "https://lumalabs.ai/dream-machine",
        "qualification": "qualifies",
        "summary": "Generative video/spatial clips arranged into explorable creative sequences.",
        "creator": "Luma AI",
        "entry_point": "https://lumalabs.ai/dream-machine",
        "accessibility": "free_account_required",
        "ai_role": "Video world model generates motion scenes from prompts and references.",
        "persistence": "generation_history",
        "platform_runtime": "Web",
        "modalities": ["video", "3d"],
        "interaction_model": "generative_scene_playback",
        "setting": "Prompt-bound generative clips.",
        "license_disclosed": "unknown",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "Public product page with generator entry.",
            "rule_2": "Users iterate prompts affecting outputs (interactive creation loop).",
            "rule_3": "Prompt defines bounded scene.",
            "rule_4": "Generation history persists for accounts.",
            "rule_5": "AI video generation is material.",
            "rule_6": "Luma AI named on site.",
            "rule_7": "Usage policies linked; age guidance sparse.",
        },
        "unknown_manifest_fields": ["world_structure.rules_or_mechanics", "experience.age_guidance"],
        "reviewer_notes": "Weaker persistence than game worlds; still passes reproducible config via generations.",
        "confidence": 0.72,
    },
    {
        "id": "wg-corpus-009",
        "name": "Polycam",
        "category": "ai_spatial",
        "canonical_source": "https://poly.cam/",
        "qualification": "qualifies",
        "summary": "Captured and generated 3D scenes users explore and share as spatial worlds.",
        "creator": "Polycam",
        "entry_point": "https://poly.cam/",
        "accessibility": "freemium_account",
        "ai_role": "AI assists reconstruction, segmentation, and scene completion.",
        "persistence": "cloud_saved_scenes",
        "platform_runtime": "Web and mobile",
        "modalities": ["3d"],
        "interaction_model": "spatial_exploration",
        "setting": "Real-world or generated captures as bounded scenes.",
        "license_disclosed": "unknown",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "poly.cam public entry to viewer and capture tools.",
            "rule_2": "Users navigate 3D captures interactively.",
            "rule_3": "Each capture is a bounded spatial artifact.",
            "rule_4": "Scenes saved to cloud accounts.",
            "rule_5": "AI reconstruction/completion documented.",
            "rule_6": "Polycam Inc. identified.",
            "rule_7": "Privacy policy published; age guidance unknown.",
        },
        "unknown_manifest_fields": ["experience.age_guidance", "ai_role.model_disclosures"],
        "reviewer_notes": "Tool-to-world boundary; qualifies when shared scenes are explorable artifacts.",
        "confidence": 0.74,
    },
    {
        "id": "wg-corpus-010",
        "name": "NVIDIA Isaac Sim",
        "category": "ai_spatial",
        "canonical_source": "https://developer.nvidia.com/isaac/sim",
        "qualification": "qualifies",
        "summary": "Robotics simulation environments with reproducible scenes and AI-driven agents.",
        "creator": "NVIDIA",
        "entry_point": "https://developer.nvidia.com/isaac/sim",
        "accessibility": "download_and_documentation",
        "ai_role": "Simulation AI for perception, control, and multi-agent robotics scenarios.",
        "persistence": "versioned_sim_configs_and_scenes",
        "agents_mechanics": "Physics simulation with robot agents and sensors.",
        "platform_runtime": "Desktop Linux/Windows",
        "modalities": ["3d", "simulation"],
        "interaction_model": "simulation_control",
        "setting": "Factory, warehouse, and lab simulation scenes.",
        "characters": "Simulated robots and actors",
        "license_disclosed": "NVIDIA software license terms",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "Developer portal with download/docs entry.",
            "rule_2": "Operators change simulation parameters and agent policies.",
            "rule_3": "Scene configs and physics rules documented.",
            "rule_4": "Versioned releases and reproducible configs.",
            "rule_5": "AI/ML simulation stack is core.",
            "rule_6": "NVIDIA as operator.",
            "rule_7": "Enterprise docs; consumer age N/A — unknown.",
        },
        "unknown_manifest_fields": ["experience.age_guidance"],
        "reviewer_notes": "Research/industrial simulation world pattern.",
        "confidence": 0.83,
    },
    # --- agent_simulation (5) ---
    {
        "id": "wg-corpus-011",
        "name": "AI Town",
        "category": "agent_simulation",
        "canonical_source": "https://github.com/a16z-infra/ai-town",
        "qualification": "qualifies",
        "summary": "Multi-agent sandbox where LLM characters interact in a persistent game map.",
        "creator": "a16z-infra (open source)",
        "entry_point": "https://github.com/a16z-infra/ai-town",
        "accessibility": "open_source_clone_and_deploy",
        "ai_role": "LLM agents plan actions and dialogue for simulated townspeople.",
        "persistence": "convex_backend_world_state",
        "agents_mechanics": "Top-down map with agent schedules and conversations.",
        "platform_runtime": "Web (self-hosted)",
        "modalities": ["2d", "text"],
        "interaction_model": "observer_and_debug_interaction",
        "setting": "Small-town simulation map.",
        "characters": "Autonomous LLM townspeople",
        "license_disclosed": "MIT",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "GitHub repo with deploy instructions.",
            "rule_2": "Agents act and converse changing world state.",
            "rule_3": "Map and agent roles bounded in repo docs.",
            "rule_4": "Backend persists agent/world state.",
            "rule_5": "LLM agents are the simulation core.",
            "rule_6": "Org/repo attribution on GitHub.",
            "rule_7": "No age policy in repo; unknown.",
        },
        "unknown_manifest_fields": ["experience.age_guidance", "trust.moderation_contact"],
        "reviewer_notes": "Canonical open-source agent society demo.",
        "confidence": 0.9,
    },
    {
        "id": "wg-corpus-012",
        "name": "Generative Agents",
        "category": "agent_simulation",
        "canonical_source": "https://github.com/joonspk-r/generative_agents",
        "qualification": "qualifies",
        "summary": "Research simulation of believable agent society in a small town (Smallville).",
        "creator": "Stanford / UW researchers",
        "entry_point": "https://github.com/joonspk-r/generative_agents",
        "accessibility": "open_source_research_artifact",
        "ai_role": "LLM-driven agents with memory and planning architectures.",
        "persistence": "simulation_logs_and_saved_states",
        "agents_mechanics": "Agent memory, reflection, and planning loops.",
        "platform_runtime": "Local Python simulation",
        "modalities": ["2d"],
        "interaction_model": "simulation_observation",
        "setting": "Smallville research environment.",
        "characters": "25 generative agents",
        "license_disclosed": "MIT (repo)",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "Public GitHub with reproduction steps.",
            "rule_2": "Agents take actions affecting environment state.",
            "rule_3": "Town map and schedules define bounds.",
            "rule_4": "Documented reproducible simulation configs.",
            "rule_5": "LLM agents central to research.",
            "rule_6": "Authors named in paper/repo.",
            "rule_7": "Research artifact; safety metadata absent.",
        },
        "unknown_manifest_fields": ["experience.age_guidance"],
        "reviewer_notes": "Seminal agent-simulation reference implementation.",
        "confidence": 0.92,
    },
    {
        "id": "wg-corpus-013",
        "name": "Voyager",
        "category": "agent_simulation",
        "canonical_source": "https://github.com/MineDojo/Voyager",
        "qualification": "qualifies",
        "summary": "LLM-powered lifelong learning agent exploring and skill-building in Minecraft.",
        "creator": "MineDojo / NVIDIA researchers",
        "entry_point": "https://github.com/MineDojo/Voyager",
        "accessibility": "open_source_with_minecraft_requirement",
        "ai_role": "LLM agent generates code/skills to act in Minecraft world.",
        "persistence": "skill_library_and_world_checkpoints",
        "agents_mechanics": "Open-ended skill acquisition in voxel world.",
        "platform_runtime": "Minecraft + Python",
        "modalities": ["3d"],
        "interaction_model": "agent_environment_loop",
        "setting": "Minecraft survival world.",
        "characters": "Voyager autonomous agent",
        "license_disclosed": "MIT",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "GitHub repo with setup instructions.",
            "rule_2": "Agent actions change Minecraft world state.",
            "rule_3": "Minecraft rules bound simulation.",
            "rule_4": "Skill library persists across runs.",
            "rule_5": "LLM is core decision engine.",
            "rule_6": "Authors/orgs on repo.",
            "rule_7": "No consumer safety docs.",
        },
        "unknown_manifest_fields": ["experience.age_guidance"],
        "reviewer_notes": "Game-world agent benchmark frequently cited in market scans.",
        "confidence": 0.91,
    },
    {
        "id": "wg-corpus-014",
        "name": "Concordia",
        "category": "agent_simulation",
        "canonical_source": "https://github.com/google-deepmind/concordia",
        "qualification": "qualifies",
        "summary": "Generative agent-based modeling library for social simulations.",
        "creator": "Google DeepMind",
        "entry_point": "https://github.com/google-deepmind/concordia",
        "accessibility": "open_source_library",
        "ai_role": "LLM agents participate in structured social simulations.",
        "persistence": "scenario_configs_and_logs",
        "agents_mechanics": "Turn-based social simulation components.",
        "platform_runtime": "Python",
        "modalities": ["text"],
        "interaction_model": "simulation_scenario",
        "setting": "Author-defined social scenarios.",
        "characters": "Generative agent cast",
        "license_disclosed": "Apache-2.0",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "Public GitHub repository.",
            "rule_2": "Agents act within simulation turns.",
            "rule_3": "Scenario definitions bound behavior.",
            "rule_4": "Configs reproducible from repo.",
            "rule_5": "LLM agents are library focus.",
            "rule_6": "DeepMind attribution.",
            "rule_7": "Research library; safety unknown.",
        },
        "unknown_manifest_fields": ["experience.age_guidance"],
        "reviewer_notes": "Library + scenarios qualify as reproducible simulation worlds.",
        "confidence": 0.87,
    },
    {
        "id": "wg-corpus-015",
        "name": "CAMEL",
        "category": "agent_simulation",
        "canonical_source": "https://github.com/camel-ai/camel",
        "qualification": "qualifies",
        "summary": "Communicative agents framework for role-playing society simulations.",
        "creator": "CAMEL-AI.org",
        "entry_point": "https://github.com/camel-ai/camel",
        "accessibility": "open_source",
        "ai_role": "Multi-agent role-playing with LLM actors cooperating on tasks.",
        "persistence": "session_and_task_logs",
        "agents_mechanics": "Role-playing agent societies and task decomposition.",
        "platform_runtime": "Python",
        "modalities": ["text"],
        "interaction_model": "multi_agent_roleplay",
        "setting": "Task-specific simulated societies.",
        "characters": "Role-playing agents",
        "license_disclosed": "Apache-2.0",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "GitHub repo with examples.",
            "rule_2": "Agents exchange messages changing task state.",
            "rule_3": "Roles/tasks bound interactions.",
            "rule_4": "Example configs reproducible.",
            "rule_5": "LLM agents are framework core.",
            "rule_6": "CAMEL-AI org on GitHub.",
            "rule_7": "No age/safety docs.",
        },
        "unknown_manifest_fields": ["experience.age_guidance"],
        "reviewer_notes": "Framework demos function as simulation worlds when scenarios run.",
        "confidence": 0.85,
    },
    # --- ai_game_ugc (5) ---
    {
        "id": "wg-corpus-016",
        "name": "Inworld Arcade",
        "category": "ai_game_ugc",
        "canonical_source": "https://inworld.ai/arcade",
        "qualification": "qualifies",
        "summary": "Playable demos showcasing AI NPCs inside game-like experiences.",
        "creator": "Inworld AI",
        "entry_point": "https://inworld.ai/arcade",
        "accessibility": "public_web_demos",
        "ai_role": "Inworld brains drive NPC dialogue and behaviors at runtime.",
        "persistence": "demo_session_state",
        "agents_mechanics": "Game-like scenes with AI NPC interactions.",
        "platform_runtime": "Web",
        "modalities": ["3d", "text", "voice"],
        "interaction_model": "game_npc_interaction",
        "setting": "Per-demo game scenes.",
        "characters": "Inworld-powered NPCs",
        "license_disclosed": "unknown",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "inworld.ai/arcade public demo hub.",
            "rule_2": "Players interact with NPCs affecting scenes.",
            "rule_3": "Each demo defines scene rules.",
            "rule_4": "Session state within demos.",
            "rule_5": "AI NPC runtime is product focus.",
            "rule_6": "Inworld AI named.",
            "rule_7": "Terms on parent site; demo age unknown.",
        },
        "unknown_manifest_fields": ["experience.age_guidance", "trust.license_status"],
        "reviewer_notes": "Issue-cited Inworld demonstration pattern.",
        "confidence": 0.84,
    },
    {
        "id": "wg-corpus-017",
        "name": "Convai Playground",
        "category": "ai_game_ugc",
        "canonical_source": "https://convai.com/",
        "qualification": "qualifies",
        "summary": "Interactive demos of conversational AI characters in 3D scenes.",
        "creator": "Convai",
        "entry_point": "https://convai.com/",
        "accessibility": "public_demos",
        "ai_role": "Convai characters hold runtime conversations and trigger scene actions.",
        "persistence": "demo_conversation_state",
        "agents_mechanics": "Voice/text NPC interactions in embedded scenes.",
        "platform_runtime": "Web embeds",
        "modalities": ["3d", "voice", "text"],
        "interaction_model": "npc_conversation",
        "setting": "Demo game and metaverse scenes.",
        "characters": "Convai NPCs",
        "license_disclosed": "unknown",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "convai.com hosts playable demos.",
            "rule_2": "Users converse with NPCs.",
            "rule_3": "Demo scenes bound interactions.",
            "rule_4": "Conversation state within sessions.",
            "rule_5": "Conversational AI is core.",
            "rule_6": "Convai Technologies identified.",
            "rule_7": "Limited age guidance.",
        },
        "unknown_manifest_fields": ["experience.age_guidance"],
        "reviewer_notes": "Issue-cited Convai demonstration pattern.",
        "confidence": 0.83,
    },
    {
        "id": "wg-corpus-018",
        "name": "Roblox AI NPC Experiences",
        "category": "ai_game_ugc",
        "canonical_source": "https://create.roblox.com/docs/ai-inference",
        "qualification": "qualifies",
        "summary": "UGC Roblox experiences using platform AI inference for NPC behavior.",
        "creator": "Roblox creators (platform docs by Roblox)",
        "entry_point": "https://create.roblox.com/docs/ai-inference",
        "accessibility": "roblox_account_required_for_play",
        "ai_role": "Roblox AI inference powers NPC dialogue/decisions in published experiences.",
        "persistence": "experience_save_data",
        "agents_mechanics": "Game mechanics with AI NPC modules.",
        "platform_runtime": "Roblox",
        "modalities": ["3d"],
        "interaction_model": "ugc_game_session",
        "setting": "Creator-defined Roblox places.",
        "characters": "AI NPCs in experiences",
        "license_disclosed": "Roblox terms",
        "safety_disclosed": "Roblox community standards",
        "criteria_evidence": {
            "rule_1": "Official docs link to AI inference in published experiences.",
            "rule_2": "Players interact in live game worlds.",
            "rule_3": "Experience rules/mechanics set bounds.",
            "rule_4": "Roblox persistence model for places.",
            "rule_5": "Material AI via inference API.",
            "rule_6": "Roblox + creators identified.",
            "rule_7": "Platform safety docs published.",
        },
        "unknown_manifest_fields": ["identity.creator per-experience", "ai_role.model_disclosures"],
        "reviewer_notes": "Corpus entry documents class of UGC worlds, not Roblox platform itself.",
        "confidence": 0.79,
    },
    {
        "id": "wg-corpus-019",
        "name": "UEFN Verse Sample Experiences",
        "category": "ai_game_ugc",
        "canonical_source": "https://dev.epicgames.com/documentation/en-us/uefn/verse-language-reference",
        "qualification": "qualifies",
        "summary": "Creator-published Fortnite UEFN islands with scripted mechanics (AI hooks emerging).",
        "creator": "Epic Games + UGC creators",
        "entry_point": "https://dev.epicgames.com/documentation/en-us/uefn/",
        "accessibility": "fortnite_client_required",
        "ai_role": "Verse scripts and emerging AI features drive NPC/logic behavior in islands.",
        "persistence": "island_published_versions",
        "agents_mechanics": "Game rules authored in Verse.",
        "platform_runtime": "Fortnite / UEFN",
        "modalities": ["3d"],
        "interaction_model": "ugc_game_session",
        "setting": "Per-island game rules.",
        "license_disclosed": "Epic developer agreements",
        "safety_disclosed": "Fortnite ratings",
        "criteria_evidence": {
            "rule_1": "UEFN docs and published island pipeline.",
            "rule_2": "Players interact in islands.",
            "rule_3": "Verse mechanics bound worlds.",
            "rule_4": "Published island versions persist.",
            "rule_5": "AI features documented for creators (evolving).",
            "rule_6": "Epic + creators identifiable.",
            "rule_7": "Fortnite age ratings apply.",
        },
        "unknown_manifest_fields": ["ai_role.model_disclosures per island"],
        "reviewer_notes": "Represents UGC game-world class from issue scope; AI materiality varies by island.",
        "confidence": 0.75,
    },
    {
        "id": "wg-corpus-020",
        "name": "VRChat AI Companion Worlds",
        "category": "ai_game_ugc",
        "canonical_source": "https://docs.vrchat.com/",
        "qualification": "qualifies",
        "summary": "User-created VRChat worlds integrating AI NPC/chat tools in social 3D spaces.",
        "creator": "VRChat creators (platform by VRChat Inc.)",
        "entry_point": "https://hello.vrchat.com/",
        "accessibility": "vrchat_account_and_client",
        "ai_role": "Third-party and official integrations add AI-driven NPCs/chat in worlds.",
        "persistence": "world_instances_and_persistence_layers",
        "agents_mechanics": "Social VR interactions with optional AI NPC plugins.",
        "platform_runtime": "VRChat",
        "modalities": ["3d", "vr", "voice"],
        "interaction_model": "social_vr_world",
        "setting": "Per-world themes and rules.",
        "characters": "AI-augmented avatars/NPCs",
        "license_disclosed": "VRChat terms",
        "safety_disclosed": "VRChat trust and safety docs",
        "criteria_evidence": {
            "rule_1": "hello.vrchat.com and docs provide entry.",
            "rule_2": "Users interact socially in world instances.",
            "rule_3": "World SDK defines bounds.",
            "rule_4": "Published worlds persist on platform.",
            "rule_5": "AI integrations documented in creator ecosystem.",
            "rule_6": "VRChat Inc. + world creators.",
            "rule_7": "Trust & safety documentation public.",
        },
        "unknown_manifest_fields": ["ai_role.model_disclosures per world"],
        "reviewer_notes": "Class entry for AI-enabled VRChat experiences, not VRChat platform alone.",
        "confidence": 0.77,
    },
    # --- persistent_social (5) ---
    {
        "id": "wg-corpus-021",
        "name": "Decentraland",
        "category": "persistent_social",
        "canonical_source": "https://decentraland.org/",
        "qualification": "qualifies",
        "summary": "Persistent virtual world where users own land and interact in real-time social economy.",
        "creator": "Decentraland Foundation",
        "entry_point": "https://decentraland.org/",
        "accessibility": "free_client_web_or_desktop",
        "ai_role": "Select scenes deploy AI guides/NPCs; ecosystem experiments documented publicly.",
        "persistence": "on_chain_land_and_scene_state",
        "agents_mechanics": "Land ownership, events, and avatar social mechanics.",
        "platform_runtime": "Web and desktop client",
        "modalities": ["3d"],
        "interaction_model": "persistent_social_world",
        "setting": "Virtual land parcels and scenes.",
        "license_disclosed": "unknown",
        "safety_disclosed": "terms of use",
        "criteria_evidence": {
            "rule_1": "decentraland.org client entry.",
            "rule_2": "Users navigate and interact socially.",
            "rule_3": "Land/scene boundaries define world structure.",
            "rule_4": "Persistent land and scene deployments.",
            "rule_5": "Documented AI NPC/guide experiments in scenes.",
            "rule_6": "Foundation named.",
            "rule_7": "Terms and policies published.",
        },
        "unknown_manifest_fields": ["ai_role.model_disclosures"],
        "reviewer_notes": "AI materiality varies by scene; qualifies at ecosystem level with documented AI deployments.",
        "confidence": 0.76,
    },
    {
        "id": "wg-corpus-022",
        "name": "Second Life",
        "category": "persistent_social",
        "canonical_source": "https://secondlife.com/",
        "qualification": "qualifies",
        "summary": "Long-running user economy MMO with persistent regions and creator-owned experiences.",
        "creator": "Linden Lab",
        "entry_point": "https://secondlife.com/",
        "accessibility": "free_account_client_download",
        "ai_role": "AI bots/NPC scripts and third-party AI tools used in regions.",
        "persistence": "region_and_inventory_persistence",
        "agents_mechanics": "Avatar social/economic interactions and land tools.",
        "platform_runtime": "Second Life viewer",
        "modalities": ["3d"],
        "interaction_model": "persistent_social_world",
        "setting": "User-created regions.",
        "license_disclosed": "Linden Lab terms",
        "safety_disclosed": "maturity ratings for regions",
        "criteria_evidence": {
            "rule_1": "secondlife.com download/play entry.",
            "rule_2": "Users affect economy and social outcomes.",
            "rule_3": "Regions have rules and themes.",
            "rule_4": "Decades-long persistent state model.",
            "rule_5": "AI bots/tools used in regions (documented community patterns).",
            "rule_6": "Linden Lab operator.",
            "rule_7": "Maturity ratings documented.",
        },
        "unknown_manifest_fields": ["ai_role.model_disclosures"],
        "reviewer_notes": "Persistent social world; AI via user scripts varies by region.",
        "confidence": 0.78,
    },
    {
        "id": "wg-corpus-023",
        "name": "Rec Room",
        "category": "persistent_social",
        "canonical_source": "https://recroom.com/",
        "qualification": "qualifies",
        "summary": "Cross-platform social VR/game world with user-created rooms and economies.",
        "creator": "Rec Room Inc.",
        "entry_point": "https://recroom.com/",
        "accessibility": "free_account_multiplatform",
        "ai_role": "AI moderation and experimental creator AI tools referenced in product updates.",
        "persistence": "user_rooms_inventory_progression",
        "agents_mechanics": "Room creation, social games, and cosmetics economy.",
        "platform_runtime": "VR and flatscreen clients",
        "modalities": ["3d", "vr"],
        "interaction_model": "persistent_social_world",
        "setting": "User-created rooms and official hubs.",
        "license_disclosed": "unknown",
        "safety_disclosed": "youth safety features documented",
        "criteria_evidence": {
            "rule_1": "recroom.com download/play funnels.",
            "rule_2": "Users interact in persistent rooms.",
            "rule_3": "Room rules/mechanics bound experiences.",
            "rule_4": "Inventory/room persistence.",
            "rule_5": "AI used in moderation/creator tooling (public posts).",
            "rule_6": "Rec Room Inc. identified.",
            "rule_7": "Youth safety pages published.",
        },
        "unknown_manifest_fields": ["ai_role.model_disclosures"],
        "reviewer_notes": "AI role includes moderation/runtime assists; not solely UGC platform.",
        "confidence": 0.74,
    },
    {
        "id": "wg-corpus-024",
        "name": "Habbo Hotel",
        "category": "persistent_social",
        "canonical_source": "https://www.habbo.com/",
        "qualification": "qualifies",
        "summary": "Persistent isometric social world with rooms, economy, and official bot characters.",
        "creator": "Sulake",
        "entry_point": "https://www.habbo.com/",
        "accessibility": "free_account_web_client",
        "ai_role": "Official bots and automated characters facilitate events and moderation.",
        "persistence": "room_layouts_and_economy",
        "agents_mechanics": "Room decorating, trading, and social games.",
        "platform_runtime": "Web",
        "modalities": ["2d"],
        "interaction_model": "persistent_social_world",
        "setting": "Hotel-themed persistent rooms.",
        "characters": "Official Habbo bots",
        "license_disclosed": "unknown",
        "safety_disclosed": "13+ and safety center",
        "criteria_evidence": {
            "rule_1": "habbo.com web client entry.",
            "rule_2": "Users interact socially and economically.",
            "rule_3": "Hotel metaphor bounds setting.",
            "rule_4": "Long-running persistent rooms/economy.",
            "rule_5": "Official bots provide automated character behavior.",
            "rule_6": "Sulake identified.",
            "rule_7": "Safety center and age policy published.",
        },
        "unknown_manifest_fields": ["ai_role.model_disclosures"],
        "reviewer_notes": "Bots provide material automated character behavior even if not LLM-based.",
        "confidence": 0.8,
    },
    {
        "id": "wg-corpus-025",
        "name": "EVE Online",
        "category": "persistent_social",
        "canonical_source": "https://www.eveonline.com/",
        "qualification": "qualifies",
        "summary": "Persistent sci-fi MMO with player-driven economy and emergent political outcomes.",
        "creator": "CCP Games",
        "entry_point": "https://www.eveonline.com/",
        "accessibility": "subscription_client",
        "ai_role": "NPC factions and market agents driven by simulation systems; AI research tools adjacent.",
        "persistence": "single_shard_universe_state",
        "agents_mechanics": "Economy, combat, and territory control.",
        "platform_runtime": "Desktop client",
        "modalities": ["3d"],
        "interaction_model": "persistent_mmo",
        "setting": "New Eden universe.",
        "characters": "NPC factions and players",
        "license_disclosed": "EULA",
        "safety_disclosed": "PEGI/ESRB ratings",
        "criteria_evidence": {
            "rule_1": "eveonline.com client entry.",
            "rule_2": "Players affect economy and territory.",
            "rule_3": "Universe lore and mechanics bounded.",
            "rule_4": "Single-shard persistence.",
            "rule_5": "Simulation-driven NPC/economy agents (material automated behavior).",
            "rule_6": "CCP Games operator.",
            "rule_7": "Age ratings disclosed.",
        },
        "unknown_manifest_fields": ["ai_role.model_disclosures"],
        "reviewer_notes": "Tests whether classical MMO simulation qualifies under AI-native definition.",
        "confidence": 0.73,
    },
    # --- negative_control (5) ---
    {
        "id": "wg-corpus-026",
        "name": "Midjourney Explore",
        "category": "negative_control",
        "canonical_source": "https://www.midjourney.com/explore",
        "qualification": "excluded",
        "exclusion_reason": "static_ai_media_only",
        "exclusion_evidence": "Gallery of generated images without interactive world state.",
        "summary": "AI image gallery for browsing generated artwork.",
        "creator": "Midjourney",
        "entry_point": "https://www.midjourney.com/explore",
        "accessibility": "account_required",
        "ai_role": "Image generation only; no interactive world loop.",
        "persistence": "unknown",
        "platform_runtime": "Web",
        "interaction_model": "passive_gallery_browsing",
        "license_disclosed": "unknown",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "Public explore URL (login may be required).",
            "rule_2": "FAIL: browsing static media, no state-changing interaction.",
            "rule_3": "No bounded world rules.",
            "rule_4": "No reproducible world config.",
            "rule_5": "AI generates images but not runtime world behavior.",
            "rule_6": "Midjourney identified.",
            "rule_7": "Terms exist; not evaluated for world access.",
        },
        "unknown_manifest_fields": [],
        "reviewer_notes": "Negative control: static AI media.",
        "confidence": 0.93,
    },
    {
        "id": "wg-corpus-027",
        "name": "ChatGPT",
        "category": "negative_control",
        "canonical_source": "https://chatgpt.com/",
        "qualification": "excluded",
        "exclusion_reason": "single_purpose_assistant",
        "exclusion_evidence": "General assistant without bounded world context.",
        "summary": "General-purpose conversational assistant.",
        "creator": "OpenAI",
        "entry_point": "https://chatgpt.com/",
        "accessibility": "free_and_paid_tiers",
        "ai_role": "General chat completion.",
        "persistence": "chat_threads",
        "platform_runtime": "Web and apps",
        "interaction_model": "single_turn_qa",
        "license_disclosed": "OpenAI terms",
        "safety_disclosed": "usage policies",
        "criteria_evidence": {
            "rule_1": "Stable public entry.",
            "rule_2": "Interaction exists but not world-like outcomes.",
            "rule_3": "FAIL: no bounded setting/mechanics.",
            "rule_4": "Threads persist but not world state.",
            "rule_5": "AI is material but assistant-only.",
            "rule_6": "OpenAI identified.",
            "rule_7": "Policies published.",
        },
        "unknown_manifest_fields": [],
        "reviewer_notes": "Negative control: generic chatbot.",
        "confidence": 0.95,
    },
    {
        "id": "wg-corpus-028",
        "name": "Unreal Engine",
        "category": "negative_control",
        "canonical_source": "https://www.unrealengine.com/",
        "qualification": "excluded",
        "exclusion_reason": "platform_product_not_world",
        "exclusion_evidence": "Game engine/SDK product, not a playable world.",
        "summary": "Real-time 3D creation engine and SDK.",
        "creator": "Epic Games",
        "entry_point": "https://www.unrealengine.com/",
        "accessibility": "download_required",
        "ai_role": "Tooling; worlds are created by downstream authors.",
        "persistence": "project_files",
        "platform_runtime": "Desktop",
        "interaction_model": "download_sdk",
        "engines": ["Unreal Engine"],
        "license_disclosed": "Epic license",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "Engine homepage stable.",
            "rule_2": "FAIL: not an experience entry point.",
            "rule_3": "Engine, not a setting.",
            "rule_4": "Projects persist but product is tooling.",
            "rule_5": "AI features assist authoring, not a world runtime.",
            "rule_6": "Epic identified.",
            "rule_7": "N/A for engine product.",
        },
        "unknown_manifest_fields": [],
        "reviewer_notes": "Linked entity type: engine/platform product.",
        "confidence": 0.94,
    },
    {
        "id": "wg-corpus-029",
        "name": "Meta Llama Model Card",
        "category": "negative_control",
        "canonical_source": "https://github.com/meta-llama/llama-models",
        "qualification": "excluded",
        "exclusion_reason": "foundation_model_or_tool_not_world",
        "exclusion_evidence": "Foundation model weights/docs without interactive world.",
        "summary": "Open foundation model family distribution.",
        "creator": "Meta",
        "entry_point": "https://github.com/meta-llama/llama-models",
        "accessibility": "open_weights_with_license",
        "ai_role": "Base model weights for downstream use.",
        "persistence": "model_checkpoints",
        "platform_runtime": "GitHub",
        "interaction_model": "download_artifact",
        "license_disclosed": "Llama license",
        "safety_disclosed": "responsible use guide",
        "criteria_evidence": {
            "rule_1": "GitHub repo entry.",
            "rule_2": "FAIL: no interactive world.",
            "rule_3": "FAIL: no bounded world setting.",
            "rule_4": "Weights reproducible but not a world.",
            "rule_5": "Model artifact, not runtime world AI.",
            "rule_6": "Meta identified.",
            "rule_7": "Responsible use docs.",
        },
        "unknown_manifest_fields": [],
        "reviewer_notes": "Negative control: foundation model.",
        "confidence": 0.96,
    },
    {
        "id": "wg-corpus-030",
        "name": "World Labs Private Beta",
        "category": "negative_control",
        "canonical_source": "https://www.worldlabs.ai/beta",
        "qualification": "excluded",
        "exclusion_reason": "no_stable_entry_point",
        "exclusion_evidence": "Login-gated beta without public reproducible artifact.",
        "summary": "Marketing/waitlist shell for private beta access.",
        "creator": "World Labs",
        "entry_point": "https://www.worldlabs.ai/beta",
        "accessibility": "login_gated",
        "ai_role": "Marketing-only claims; no observable runtime AI in public beta shell.",
        "persistence": "unknown",
        "platform_runtime": "Web",
        "interaction_model": "waitlist_signup",
        "license_disclosed": "unknown",
        "safety_disclosed": "unknown",
        "criteria_evidence": {
            "rule_1": "FAIL: no public playable artifact without auth.",
            "rule_2": "No interactive experience available.",
            "rule_3": "No observable world rules.",
            "rule_4": "FAIL: no reproducible config.",
            "rule_5": "AI claims marketing-only.",
            "rule_6": "World Labs named.",
            "rule_7": "Cannot evaluate access safely.",
        },
        "unknown_manifest_fields": ["ai_role.material_ai_role", "experience.persistence_model"],
        "reviewer_notes": "Negative control: inaccessible/login-gated demo.",
        "confidence": 0.88,
    },
]


def seed_to_candidate(seed: dict[str, Any]) -> dict[str, Any]:
    manifest_file = f"manifests/{seed['id']}.json"
    return {
        "id": seed["id"],
        "name": seed["name"],
        "category": seed["category"],
        "canonical_source": seed["canonical_source"],
        "qualification": seed["qualification"],
        "last_checked": LAST_CHECKED,
        "source_first_seen": "2026-07-22",
        "criteria_evidence": seed["criteria_evidence"],
        "creator": seed["creator"],
        "operator": seed.get("operator"),
        "entry_point": seed["entry_point"],
        "accessibility": seed["accessibility"],
        "ai_role": seed["ai_role"],
        "persistence": seed["persistence"],
        "agents_mechanics": seed.get("agents_mechanics"),
        "platform_runtime": seed.get("platform_runtime"),
        "license_disclosed": seed.get("license_disclosed", "unknown"),
        "safety_disclosed": seed.get("safety_disclosed", "unknown"),
        "unknown_manifest_fields": seed.get("unknown_manifest_fields", []),
        "reviewer_notes": seed["reviewer_notes"],
        "confidence": seed["confidence"],
        "manifest_file": manifest_file,
        "exclusion_reason": seed.get("exclusion_reason"),
    }


def write_candidates_yaml(candidates: list[dict[str, Any]]) -> None:
    yaml = __import__("yaml")
    payload = {
        "schema_version": "worldgraph-research-corpus-v1",
        "research_only": True,
        "not_for_public_index": True,
        "description": (
            "Source-backed research corpus for WorldGraph product definition (issue #200). "
            "Not production content. Not automatically published."
        ),
        "parent_issue": 200,
        "depends_on_issue": 199,
        "last_updated": LAST_CHECKED,
        "candidates": candidates,
    }
    path = CORPUS_ROOT / "candidates.yaml"
    path.write_text(
        yaml.dump(payload, sort_keys=False, allow_unicode=True, default_flow_style=False),
        encoding="utf-8",
    )
    json_path = CORPUS_ROOT / "candidates.json"
    json_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def validate_all(candidates: list[dict[str, Any]]) -> dict[str, Any]:
    jsonschema = __import__("jsonschema")
    schema = json.loads((REPO_ROOT / "docs/worldgraph/world-manifest-v0.schema.json").read_text())
    validator = jsonschema.Draft202012Validator(schema)
    results: list[dict[str, Any]] = []
    for candidate in candidates:
        manifest_path = CORPUS_ROOT / candidate["manifest_file"]
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        entry: dict[str, Any] = {
            "id": candidate["id"],
            "name": candidate["name"],
            "qualification": candidate["qualification"],
            "manifest_file": candidate["manifest_file"],
        }
        schema_error: str | None = None
        spike_error: str | None = None
        try:
            validator.validate(manifest)
        except Exception as exc:  # noqa: BLE001 - collect validation errors
            schema_error = str(exc)
        try:
            validate_manifest_v0(manifest)
        except Exception as exc:  # noqa: BLE001 - spike helper stricter on some fields
            spike_error = str(exc)
        entry["schema_valid"] = schema_error is None
        entry["spike_valid"] = spike_error is None
        entry["error"] = schema_error or spike_error
        results.append(entry)
    qualifying = [r for r in results if r["qualification"] == "qualifies"]
    return {
        "generated_at": OBSERVED_AT,
        "schema_version": "world-manifest-v0",
        "total_candidates": len(results),
        "qualifying_count": len(qualifying),
        "qualifying_validation": [r for r in results if r["qualification"] == "qualifies"],
        "all_results": results,
    }


def main() -> int:
    MANIFESTS_DIR.mkdir(parents=True, exist_ok=True)
    candidates = [seed_to_candidate(seed) for seed in CORPUS_SEEDS]
    for seed in CORPUS_SEEDS:
        manifest = build_manifest(seed)
        out_path = MANIFESTS_DIR / f"{seed['id']}.json"
        out_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    write_candidates_yaml(candidates)
    validation = validate_all(candidates)
    VALIDATION_RESULTS_PATH.write_text(json.dumps(validation, indent=2) + "\n", encoding="utf-8")
    failed = [
        r
        for r in validation["all_results"]
        if not r.get("schema_valid") and r["qualification"] == "qualifies"
    ]
    if failed:
        print(f"Validation failed for {len(failed)} entries", file=sys.stderr)
        for item in failed:
            print(f"  {item['id']}: {item['error']}", file=sys.stderr)
        return 1
    print(
        f"Wrote {len(candidates)} candidates, "
        f"{validation['qualifying_count']} qualifying manifests validated."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
