"""CRM repository exports."""

from app.repositories.postgres import (
    PostgresAcquisitionDashboardRepository,
    PostgresMarketingAnalyticsRepository,
    PostgresActivityRepository,
    PostgresAdminUserRepository,
    PostgresAuditEventRepository,
    PostgresCompanyRepository,
    PostgresContactRepository,
    PostgresImportBatchRepository,
    PostgresIcpScoringRepository,
    PostgresPipelineRepository,
    PostgresProjectBriefRepository,
    PostgresRepositories,
    PostgresResearchRecordRepository,
    PostgresSourceRecordRepository,
    default_repositories,
    get_repositories,
)
from app.repositories.protocols import (
    AcquisitionDashboardRepository,
    MarketingAnalyticsRepository,
    ActivityRepository,
    AdminUserRepository,
    AuditEventRepository,
    CompanyRepository,
    ContactRepository,
    IcpScoringRepository,
    ImportBatchRepository,
    PipelineRepository,
    ProjectBriefRepository,
    ResearchRecordRepository,
    SourceRecordRepository,
)

__all__ = [
    "AcquisitionDashboardRepository",
    "MarketingAnalyticsRepository",
    "ActivityRepository",
    "AdminUserRepository",
    "AuditEventRepository",
    "CompanyRepository",
    "ContactRepository",
    "IcpScoringRepository",
    "ImportBatchRepository",
    "PipelineRepository",
    "ProjectBriefRepository",
    "ResearchRecordRepository",
    "SourceRecordRepository",
    "PostgresAcquisitionDashboardRepository",
    "PostgresMarketingAnalyticsRepository",
    "PostgresActivityRepository",
    "PostgresAdminUserRepository",
    "PostgresAuditEventRepository",
    "PostgresCompanyRepository",
    "PostgresContactRepository",
    "PostgresImportBatchRepository",
    "PostgresIcpScoringRepository",
    "PostgresPipelineRepository",
    "PostgresProjectBriefRepository",
    "PostgresRepositories",
    "PostgresResearchRecordRepository",
    "PostgresSourceRecordRepository",
    "default_repositories",
    "get_repositories",
]
