"""CRM repository package."""

from app.repositories.postgres import (
    PostgresAcquisitionDashboardRepository,
    PostgresActivityRepository,
    PostgresAdminUserRepository,
    PostgresAuditEventRepository,
    PostgresCompanyRepository,
    PostgresContactRepository,
    PostgresProjectBriefRepository,
    PostgresRepositories,
    PostgresResearchRecordRepository,
    PostgresSourceRecordRepository,
    PostgresStageHistoryRepository,
    default_repositories,
    get_repositories,
)
from app.repositories.protocols import (
    AcquisitionDashboardRepository,
    ActivityRepository,
    AdminUserRepository,
    AuditEventRepository,
    CompanyRepository,
    ContactRepository,
    ProjectBriefRepository,
    ResearchRecordRepository,
    SourceRecordRepository,
    StageHistoryRepository,
)

__all__ = [
    "AcquisitionDashboardRepository",
    "ActivityRepository",
    "AdminUserRepository",
    "AuditEventRepository",
    "CompanyRepository",
    "ContactRepository",
    "ProjectBriefRepository",
    "ResearchRecordRepository",
    "SourceRecordRepository",
    "StageHistoryRepository",
    "PostgresAcquisitionDashboardRepository",
    "PostgresActivityRepository",
    "PostgresAdminUserRepository",
    "PostgresAuditEventRepository",
    "PostgresCompanyRepository",
    "PostgresContactRepository",
    "PostgresProjectBriefRepository",
    "PostgresRepositories",
    "PostgresResearchRecordRepository",
    "PostgresSourceRecordRepository",
    "PostgresStageHistoryRepository",
    "default_repositories",
    "get_repositories",
]
